# For detailed configuration guide(In Chinese): https://irine-sistiana.gitbook.io/mosdns-wiki/

log:
  level: info

data_providers:
  - tag: geosite
    file: "/etc/mosdns/dlc.dat"
    auto_reload: true
  - tag: geoip
    file: "/etc/mosdns/geoip.dat"
    auto_reload: true
  - tag: gfwip
    file: ./rules/gfw_ip_list.txt
    auto_reload: true
  - tag: "mem_cache"
    type: "cache"
    args:
      size: 40960
      lazy_cache_ttl: 259200
      lazy_cache_reply_ttl: 30
      cache_everything: true

plugins:
  - tag: forward_query_to_fallback_cloudflare
    type: fast_forward
    args:
      upstream:
        - addr: 'https://cloudflare-dns.com/dns-query'
          dial_addr: '1.0.0.1:443'
          trusted: true
        - addr: 'https://cloudflare-dns.com/dns-query'
          dial_addr: '1.1.1.1:443'
          trusted: true
        - addr: 'tls://cloudflare-dns.com'
          dial_addr: '1.0.0.1:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://cloudflare-dns.com'
          dial_addr: '1.1.1.1:853'
          enable_pipeline: true
          trusted: true
  - tag: forward_query_to_fallback_dnssb
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.sb/dns-query'
          dial_addr: '185.222.222.222:443'
          trusted: true
        - addr: 'https://doh.sb/dns-query'
          dial_addr: '45.11.45.11:443'
          trusted: true
        - addr: 'tls://dot.sb'
          dial_addr: '185.222.222.222:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dot.sb'
          dial_addr: '45.11.45.11:853'
          enable_pipeline: true
          trusted: true

  - tag: forward_query_to_fallback_quad9
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns10.quad9.net/dns-query'
          dial_addr: '149.112.112.10:443'
          trusted: true
        - addr: 'https://dns10.quad9.net/dns-query'
          dial_addr: '9.9.9.10:443'
          trusted: true
        - addr: 'tls://dns10.quad9.net'
          dial_addr: '149.112.112.10:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dns10.quad9.net'
          dial_addr: '9.9.9.10:853'
          enable_pipeline: true
          trusted: true
  - tag: forward_query_to_local_360
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '101.226.4.6:443'
          trusted: true
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '123.125.81.6:443'
          trusted: true
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '140.207.198.6:443'
          trusted: true
        - addr: 'https://doh.360.cn/dns-query'
          dial_addr: '218.30.118.6:443'
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '101.226.4.6:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '123.125.81.6:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '140.207.198.6:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '218.30.118.6:853'
          enable_pipeline: false
          trusted: true
  - tag: forward_query_to_local_alidns
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
          trusted: true
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: false
          trusted: true

  - tag: forward_query_to_local_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
          trusted: true
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
          trusted: true
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: true
          trusted: true
  - tag: forward_query_to_remote_adguard
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns-unfiltered.adguard.com/dns-query'
          dial_addr: '94.140.14.140:443'
          trusted: true
        - addr: 'https://dns-unfiltered.adguard.com/dns-query'
          dial_addr: '94.140.14.141:443'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.140:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.141:853'
          enable_pipeline: true
          trusted: true

  - tag: forward_query_to_remote_google
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.4.4:443'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          enable_pipeline: true
          trusted: true

  - tag: forward_query_to_remote_opendns
    type: fast_forward
    args:
      upstream:
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.220.2:443'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.222.2:443'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          enable_pipeline: true
          trusted: true

  - tag: query_is_blacklist_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:category-ads'
      # - 'provider:geosite:category-porn'
      # - "example.example"
  # For more info on geosite: https://github.com/v2fly/domain-list-community/tree/master/data
  # 匹配污染IP的插件
  - tag: response_has_gfw_ip
    type: response_matcher
    args:
      ip:
        - "provider:gfwip"
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'
      # - "192.168.1.1/24"
  # geoip support two-letter country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
  - tag: match_qtype65
    type: query_matcher
    args:
      qtype: [65]
  - tag: response_has_valid_rcode
    type: response_matcher
    args:
      rcode: [0]
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: set_edns0_client_subnet
    type: ecs
    args:
      auto: true
      mask4: 24
      mask6: 56
  - tag: main_server
    type: sequence
    args:
      exec:
        - _enable_response_padding
        - _misc_optm
        - set_edns0_bufsize
        - set_edns0_client_subnet
        - _pad_query
        - mem_cache
        - if: "query_is_blacklist_domain || match_qtype65"
          exec:
            - _new_nxdomain_response
            - _return
        - primary:
            - parallel:
                - - forward_query_to_local_360
                - - forward_query_to_local_alidns
                - - forward_query_to_local_dnspod
            - if: '((! response_has_local_ip) && [_response_valid_answer]) || (! response_has_valid_rcode) || (response_has_gfw_ip)'
              exec:
                - _drop_response
          secondary:
            - primary:
                - parallel:
                    - - forward_query_to_remote_adguard
                    - - forward_query_to_remote_google
                    - - forward_query_to_remote_opendns
                - if: '(! response_has_valid_rcode)'
                  exec:
                    - _drop_response
              secondary:
                - parallel:
                    - - forward_query_to_fallback_cloudflare
                    - - forward_query_to_fallback_dnssb
                    - - forward_query_to_fallback_quad9
              always_standby: true
              fast_fallback: 625
          always_standby: false
          fast_fallback: 375
servers:
  - exec: main_server
    timeout: 5    
    listeners:   
      - protocol: http
        addr: ":PORT_PLACEHOLDER"   
        url_path: "PATH_PLACEHOLDER"
        get_user_ip_from_header: "X-Forwarded-For"
